# Generated by Django 3.2.9 on 2021-12-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtenteRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=12)),
                ('cogno', models.CharField(default='', max_length=20)),
                ('tele', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UtenteAppuntamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataa', models.DateTimeField()),
                ('nomeu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.utenterubrica')),
            ],
        ),
    ]
